[tools]
fzf = "latest"
shfmt = "latest"
lazygit = "latest"
go = "latest"
bun = "latest"
java = "17"
node = "20"
ruby = "3.2.2"
python = "3.12"

[settings]
activate_aggressive = true
experimental = true
