live_config_reload = true

shell = "/bin/zsh"

import = ["~/.config/alacritty/catppuccin-latte.toml"]

[env]
term = "xterm-256color"
ALACRITTY = "true"

[window]
dynamic_title = true
decorations_theme_variant = "None"
option_as_alt = "OnlyLeft"

[cursor]
thickness = 0.85
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "off"

[terminal]
osc52 = "CopyPaste"

[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"
