[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "dprint", args = ["fmt", "--stdin", "js"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "dprint", args = ["fmt", "--stdin", "ts"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "dprint", args = ["fmt", "--stdin", "sh"] }
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
