#!/bin/bash

# WRITTEN BY CHATGPT
# Define the fixed location
fixed_location="$HOME/dotfiles"

# Loop through all subdirectories
for subdir in "$fixed_location"/*; do
	if [ -d "$subdir" ]; then
		subdir_name=$(basename "$subdir")
		if [ "$subdir_name" = "scripts" ]; then
			stow -t "$HOME/.local/bin" --ignore="install" scripts
		elif [ "$subdir_name" = "raycast" ] || [ "$subdir_name" = "stylus" ] || [ "$subdir_name" = "karabiner" ]; then
			continue
		else
			stow --no-folding "$subdir_name"
		fi
	fi
done
