#!/bin/bash

# WRITTEN BY CHATGPT
# Define the fixed location
fixed_location="/home/fjorn/dotfiles"

# Loop through all subdirectories
for subdir in "$fixed_location"/*; do
	if [ -d "$subdir" ]; then
		subdir_name=$(basename "$subdir")
		if [ "$subdir_name" = "scripts" ]; then
			stow -t '/home/fjorn/.local/bin' --ignore='install' scripts
		else
			stow --no-folding "$subdir_name"
		fi
	fi
done
