#!/bin/bash

# WRITTEN BY CHAT GPT
# Word to add to the dictionary
read -r word

# TOML file path
toml_file="/home/fjorn/dotfiles/helix/.config/helix/languages.toml"

# Check if the TOML file exists

if [ ! -f "$toml_file" ]; then
	echo "TOML file not found: $toml_file"
	exit 2
fi

# Add the word to the dictionary using awk
awk -v word="$word" '/ltex\.dictionary/ && /en-US/ {gsub(/\]/, ", \"" word "\"]")} 1' "$toml_file" >tmpfile && mv tmpfile "$toml_file"
