#!/bin/bash

# Function to display usage
usage() {
	echo "Usage: $0 filename [--light|--dark] [--quotes] [--underscore]"
	exit 1
}

# Check if at least one argument is given
if [ $# -lt 1 ]; then
	usage
fi

# Store the file name from the arguments
FILE=$1

# Check if the file exists
if [ ! -e "$FILE" ]; then
	echo "File not found!"
	exit 1
fi

# Determine the actual file the symlink points to, if applicable
TARGET_FILE=$(readlink -f "$FILE" || echo "$FILE")

# Initialize variables for the options
LIGHT_REPLACEMENT="catppuccin-latte"
DARK_REPLACEMENT="catppuccin-macchiato"
USE_QUOTES=false
USE_UNDERSCORE=false

# Process the flags
for arg in "$@"; do
	case $arg in
	--light)
		REPLACEMENT_ACTION="light"
		;;
	--dark)
		REPLACEMENT_ACTION="dark"
		;;
	--quotes)
		USE_QUOTES=true
		;;
	--underscore)
		USE_UNDERSCORE=true
		;;
	*)
		FILE_ARG="$arg"
		;;
	esac
done

# Adjust replacements based on flags
if [ "$USE_UNDERSCORE" = true ]; then
	LIGHT_REPLACEMENT="catppuccin_latte"
	DARK_REPLACEMENT="catppuccin_macchiato"
fi

if [ "$USE_QUOTES" = true ]; then
	LIGHT_REPLACEMENT="\"$LIGHT_REPLACEMENT\""
	DARK_REPLACEMENT="\"$DARK_REPLACEMENT\""
fi

# Perform the replacement based on the selected action
if [ "$REPLACEMENT_ACTION" == "light" ]; then
	sed -E "s/$DARK_REPLACEMENT/$LIGHT_REPLACEMENT/g" "$TARGET_FILE" >/tmp/tmpfile && mv /tmp/tmpfile "$TARGET_FILE"
elif [ "$REPLACEMENT_ACTION" == "dark" ]; then
	sed -E "s/$LIGHT_REPLACEMENT/$DARK_REPLACEMENT/g" "$TARGET_FILE" >/tmp/tmpfile && mv /tmp/tmpfile "$TARGET_FILE"
else
	usage
fi
